---
- name: Install utils
  tags: utils
  become: true
  block:
    - name: Install
      apt:
        name:
          - htop
          - vim
          - git
          - tree
          - tmux
          - gnupg
          - rsync
          - bash-completion
        update_cache: true
        cache_valid_time: 86400
